name = "spino-gambino-casino-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambino-casino.com.de"
HMAC_KEY = "afeb40f479574b6761e2689c103c40f15eaf922cc231ba2efeb6173ae25cd2b4"
COOKIE_NAME = "z8x"
PLAY_PATH = "play-now"
BUTTON_ID = "pce11ba9db6686d415dfb6781a203bd77"
GATE_SALT = "ea1ab93adffbb6e6"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "l5jd"
CTA_SELECTOR = ".play-button"
